language: c

matrix:
  include:

    # ###### Ubuntu Linux ###################################################

    # ====== Ubuntu 18.10 (Cosmic Cuttlefish) ===============================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:cosmic" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:cosmic" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:cosmic" VARIANT="ubuntu" TOOL="pbuilder"

    # ====== Ubuntu 18.04 (Bionic Beaver) ===================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="pbuilder"

    # ====== Ubuntu 16.04 (Xenial Xerus) ====================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" TOOL="pbuilder"


     # ###### Debian Linux ##################################################

     # ====== Debian Testing ================================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:testing" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:testing" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:testing" VARIANT="debian" TOOL="pbuilder"

    # ====== Debian Sid =====================================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:sid" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:sid" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:sid" VARIANT="debian" TOOL="pbuilder"

    # ====== Debian Buster ==================================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:buster" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:buster" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:buster" VARIANT="debian" TOOL="pbuilder"

    # ====== Debian Stretch =================================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:stretch" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:stretch" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:stretch" VARIANT="debian" TOOL="pbuilder"


    ## ###### Fedora Linux ###################################################

    # ====== Fedora 30 ======================================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:30" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:30" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:30" VARIANT="fedora" TOOL="mock"

    # ====== Fedora 29 ======================================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:29" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:29" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:29" VARIANT="fedora" TOOL="mock"

    # ====== Fedora 28 ======================================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:28" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:28" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:28" VARIANT="fedora" TOOL="mock"

    # ====== Fedora Rawhide =================================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:rawhide" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:rawhide" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:rawhide" VARIANT="fedora" TOOL="mock"


    # ###### Other ##########################################################

    # ====== MacOS X ========================================================
    #- os: osx
    #  osx_image: xcode9.4
    #  compiler: clang
    #  group: travis_latest


before_install:
  - |
    ci/before-install


install:
  - |
    ci/install


script:
  - |
    ci/build
